import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'PT';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        nav_services: 'Services',
        nav_areas: 'Areas',
        nav_gallery: 'Gallery',
        nav_reviews: 'Reviews',
        nav_contact: 'Contact',
        nav_free_quote: 'Free Quote',
        nav_brand: 'Antigravity',
        hero_title_1: 'Elevate Your Business',
        hero_title_2: ' with Antigravity',
        hero_desc: 'We specialize in premium website development, AI-powered automation, and custom CRM solutions for businesses looking to scale effortlessly.',
        hero_cta: 'Get a Free Quote',
        hero_social_proof: 'Rated 4.9 · 60+ Google Reviews',
        hero_hours: 'Mon to Sat, 7am to 6pm. Free quotes with no obligation. We usually reply within 2 hours.',
        cred_title_1: 'Secure & Scalable',
        cred_subtitle_1: 'Enterprise-Grade Code',
        cred_title_2: 'Fast Delivery',
        cred_subtitle_2: 'Agile Development',
        cred_title_3: 'AI Specialists',
        cred_subtitle_3: 'Expert LLM Integration',
        cred_title_4: '5.0 Rating',
        cred_subtitle_4: 'Happy Global Clients',
        how_title: 'Simple From Start to Finish',
        how_desc: 'We keep things straightforward. No chasing, no surprises, just good work done properly.',
        how_step1_title: 'Get in Touch',
        how_step1_desc: 'Call us or fill in our quick form. We usually respond within 2 hours and can visit for a quote the same week.',
        how_step2_title: 'Free Quote & Schedule',
        how_step2_desc: 'We visit, assess the work and give you a clear written quote. No hidden costs. You choose a start date that suits you.',
        how_step3_title: 'Pristine Results',
        how_step3_desc: 'We work cleanly, protect your furniture and leave the place spotless. Most of our clients come back to us for their next job.',
        how_cta: 'Call Now: 07384 631028',
        landlord_badge: 'For Landlords & Letting Agents',
        landlord_title: 'Fast Turnarounds.\nMinimal Disruption.\nTenancy-Ready Results.',
        landlord_desc: 'We work with landlords and letting agents across Ely and Cambridgeshire to get properties back on the market quickly.',
        landlord_cta_1: 'Property Owner Enquiry',
        landlord_feat1_title: 'End-of-Tenancy Work',
        landlord_feat1_desc: 'We know what letting inspections look for. Clean, crisp finishes that satisfy agents and tenants alike.',
        landlord_feat2_title: 'Portfolio Maintenance',
        landlord_feat2_desc: 'Regular maintenance across multiple properties. One point of contact and a consistent standard every time.',
        landlord_feat3_title: 'Flexible Scheduling',
        landlord_feat3_desc: 'We work around void periods, tenant move-outs and inspection timelines.',
        landlord_feat4_title: 'Clear Invoicing',
        landlord_feat4_desc: 'Detailed invoices for every job, easy to pass on to landlords or use for tenant deposit deductions.',
        gallery_title: 'Our Work Across Cambridgeshire',
        gallery_desc: 'From Ely townhouses to Cambridge period homes, we hold the same high standard on every job.',
        gallery_cta: 'Request a similar finish',
        reviews_title: 'What Our Customers Say',
        reviews_subtitle: 'Trusted by homeowners and landlords across Ely, Cambridge, and Cambridgeshire.',
        reviews_proof: '4.9 average · 60+ Google Reviews',
        reviews_source: 'Reviews sourced from Google Business Profile',
        review_1_text: 'The team transformed our Victorian townhouse with incredible attention to detail. Immaculate, quiet, and the finish on the woodwork is simply flawless. Worth every penny.',
        review_2_text: 'Finding reliable tradespeople in Cambridgeshire is hard — they are in a league of their own. They helped us with our kitchen fitting and the result was brilliant.',
        review_3_text: 'Professional from the first quote to the final walkthrough. They repaired extensive water damage before painting and you would never know it was there. Highly recommended.',
        review_4_text: 'I use them for all my rental properties. Fast, tidy, and consistently brilliant. My tenants comment on how well the properties are presented. The best trade I have ever found.',
        review_5_text: 'Booked them for a full exterior repaint and they were outstanding. They flagged some rot issues I didn\'t noticed, repaired them, and the house looks like new. Will use again.',
        review_6_text: 'Gave us a clear quote, stuck to it, and completed ahead of schedule. Covered everything carefully and left zero mess. Exactly what you want from a tradesperson.',
        services_title: 'What We Do',
        services_desc: 'Full property care from a quick repaint to a complete interior refresh. One reliable team, one point of contact.',
        services_cta: 'Enquire About Any Service',
        service_s1_title: 'Web Application Development',
        service_s1_desc: 'Custom React and Next.js applications built for performance, scalability, and exceptional user experience.',
        service_s2_title: 'AI Automation & Agents',
        service_s2_desc: 'Integrate advanced AI workflows into your business processes to automate repetitive tasks and gain insights.',
        service_s3_title: 'CRM & Lead Management',
        service_s3_desc: 'Specialized systems like EuroBras CRM to manage your leads, track performance, and boost conversions.',
        service_s4_title: 'Responsive UI/UX Design',
        service_s4_desc: 'Modern, vibrant designs that WOW your users and feel premium across all devices and screen sizes.',
        service_s5_title: 'Cloud Infrastructure',
        service_s5_desc: 'Scalable deployment models on Netlify, Vercel, or AWS with automated CI/CD pipelines and high availability.',
        service_s6_title: 'Data Enrichment',
        service_s6_desc: 'Scrape, process, and enrich your business data using custom Python and JavaScript pipelines for better leads.',
        area_badge: 'Service Area',
        area_title: 'Covering Ely, Cambridge & Surrounding Cambridgeshire',
        area_desc1: 'Based in Ely, we carry out house maintenance, handyman work, painting, carpentry, kitchens and bathrooms, and landscaping across Cambridgeshire.',
        area_desc2: 'Not sure if we cover your area? Give us a call. We are flexible and regularly take on work all across the fens.',
        area_label: 'Areas We Cover',
        contact_title: 'Get Your Free Quote',
        contact_desc: 'Fill in the form and we will get back to you within 2 hours. Prefer to talk? Give us a call.',
        contact_phone_label: 'Call or WhatsApp',
        contact_email_label: 'Email Us',
        contact_hours_label: 'Working Hours',
        contact_hours_val: 'Mon–Sat, 7am–6pm',
        contact_reason_title: 'Why clients choose us',
        contact_r1: 'Free written quotes, no obligation',
        contact_r2: 'Fixed prices with no hidden extras',
        contact_r3: 'Tidy, professional and respectful of your home',
        contact_r4: 'Fully insured to £5M public liability',
        contact_form_title: 'Tell Us About Your Job',
        contact_form_name: 'Name',
        contact_form_name_ph: 'Your name',
        contact_form_phone: 'Phone',
        contact_form_phone_ph: 'Best number to call',
        contact_form_email: 'Email',
        contact_form_email_ph: 'Your email address',
        contact_form_service: 'Service Needed',
        contact_form_submit: 'Get a Free Quote',
        contact_success_title: 'Message Received!',
        contact_success_desc: 'Thank you. We will be in touch within 2 hours.',
        contact_field_project: 'Tell Us About Your Project',
        contact_field_project_ph: 'E.g. 3-bed semi in Ely...',
        contact_reply_time: 'We usually reply within 2 hours. No obligation and no hard sell.',
        gallery_img1_label: 'Custom CRM Dashboard',
        gallery_img2_label: 'E-commerce Solutions',
        gallery_img3_label: 'AI Agent Workflows',
        gallery_img4_label: 'Next.js App Directory',
        footer_desc: 'House maintenance, handyman work, painting, carpentry, kitchens, bathrooms and landscaping across Cambridgeshire.',
        footer_privacy: 'Privacy Policy',
        footer_terms: 'Terms of Service',
    },
    PT: {
        nav_services: 'Serviços',
        nav_areas: 'Áreas',
        nav_gallery: 'Galeria',
        nav_reviews: 'Avaliações',
        nav_contact: 'Contato',
        nav_free_quote: 'Orçamento Grátis',
        nav_brand: 'Antigravity',
        hero_title_1: 'Eleve seu Negócio',
        hero_title_2: ' com Antigravity',
        hero_desc: 'Especializamo-nos em desenvolvimento de websites premium, automação via IA e soluções de CRM personalizadas para empresas que buscam escalar sem esforço.',
        hero_cta: 'Solicitar Orçamento',
        hero_social_proof: 'Avaliado em 4.9 · 60+ Avaliações no Google',
        hero_hours: 'Seg a Sáb, das 7h às 18h. Orçamentos sem compromisso. Respondemos em até 2 horas.',
        cred_title_1: 'Seguro & Escalável',
        cred_subtitle_1: 'Código de Nível Corporativo',
        cred_title_2: 'Entrega Rápida',
        cred_subtitle_2: 'Desenvolvimento Ágil',
        cred_title_3: 'Especialistas em IA',
        cred_subtitle_3: 'Integração de LLM Expert',
        cred_title_4: 'Avaliação 5.0',
        cred_subtitle_4: 'Clientes Globais Satisfeitos',
        how_title: 'Simples do Início ao Fim',
        how_desc: 'Sem complicações. Sem surpresas. Só um bom trabalho feito com cuidado.',
        how_step1_title: 'Entre em Contato',
        how_step1_desc: 'Ligue ou preencha nosso formulário rápido. Geralmente respondemos em 2 horas e podemos visitar para orçamento na mesma semana.',
        how_step2_title: 'Orçamento Grátis & Agendamento',
        how_step2_desc: 'Visitamos, avaliamos o trabalho e entregamos um orçamento escrito e claro. Sem custos ocultos. Você escolhe a data de início.',
        how_step3_title: 'Resultado Impecável',
        how_step3_desc: 'Trabalhamos limpamente, protegemos seus móveis e deixamos tudo em ordem. A maioria dos nossos clientes volta para o próximo serviço.',
        how_cta: 'Ligar Agora: 07384 631028',
        landlord_badge: 'Para Proprietários & Imobiliárias',
        landlord_title: 'Entrega Rápida.\nMínima Perturbação.\nResultado Pronto para Locação.',
        landlord_desc: 'Trabalhamos com proprietários e imobiliárias em Ely e Cambridgeshire para colocar imóveis de volta no mercado rapidamente.',
        landlord_cta_1: 'Consulta para Proprietário',
        landlord_feat1_title: 'Trabalho no Fim do Contrato',
        landlord_feat1_desc: 'Sabemos o que as vistorias de locação exigem. Acabamentos limpos e precisos que satisfazem agentes e inquilinos.',
        landlord_feat2_title: 'Manutenção de Portfólio',
        landlord_feat2_desc: 'Manutenção regular em múltiplos imóveis. Um único ponto de contato e um padrão consistente sempre.',
        landlord_feat3_title: 'Agendamento Flexível',
        landlord_feat3_desc: 'Trabalhamos em torno dos períodos vagos, saída de inquilinos e prazos de vistoria.',
        landlord_feat4_title: 'Faturamento Claro',
        landlord_feat4_desc: 'Faturas detalhadas para cada serviço, fáceis de repassar a proprietários ou usar para deduções de caução.',
        gallery_title: 'Nossos Trabalhos por Cambridgeshire',
        gallery_desc: 'De casas em Ely a imóveis históricos em Cambridge, mantemos o mesmo alto padrão em cada serviço.',
        gallery_cta: 'Solicite um acabamento similar',
        reviews_title: 'O Que Nossos Clientes Dizem',
        reviews_subtitle: 'Confiados por proprietários e locadores em Ely, Cambridge e Cambridgeshire.',
        reviews_proof: 'Média 4,9 · Mais de 60 avaliações no Google',
        reviews_source: 'Avaliações extraídas do Google Meu Negócio',
        review_1_text: 'A equipe transformou nossa casa vitoriana com uma atenção incrível aos detalhes. Implacáveis, silenciosos e o acabamento na marcenaria é simplesmente impecável. Valeu cada centavo.',
        review_2_text: 'Encontrar profissionais confiáveis em Cambridgeshire é difícil — eles estão em outro nível. Eles nos ajudaram com a instalação da cozinha e o resultado foi brilhante.',
        review_3_text: 'Profissionais desde o primeiro orçamento até a vistoria final. Repararam danos extensos causados por água antes da pintura e você nunca saberia que estavam lá. Altamente recomendados.',
        review_4_text: 'Eu os utilizo para todas as minhas propriedades de aluguel. Rápidos, organizados e consistentemente brilhantes. Meus inquilinos comentam como os imóveis estão bem apresentados.',
        review_5_text: 'Contratei para uma repintura externa completa e eles foram excepcionais. Identificaram problemas de apodrecimento que eu não tinha notado, repararam e a casa parece nova. Usarei novamente.',
        review_6_text: 'Deram um orçamento claro, cumpriram o valor e terminaram antes do prazo. Cobriram tudo com cuidado e não deixaram nenhuma sujeira. Exatamente o que se espera de um profissional.',
        services_title: 'O Que Fazemos',
        services_desc: 'Cuidado completo do imóvel, de uma repintura rápida a uma reforma completa do interior. Uma equipe confiável, um único ponto de contato.',
        services_cta: 'Consultar Sobre Qualquer Serviço',
        service_s1_title: 'Desenvolvimento de Web Apps',
        service_s1_desc: 'Aplicações personalizadas em React e Next.js focadas em performance, escalabilidade e experiência do usuário.',
        service_s2_title: 'Automação de IA & Agentes',
        service_s2_desc: 'Integre fluxos avançados de IA nos seus processos para automatizar tarefas repetitivas e obter insights.',
        service_s3_title: 'CRM & Gestão de Leads',
        service_s3_desc: 'Sistemas especializados como o EuroBras CRM para gerir seus leads, monitorar performance e aumentar conversões.',
        service_s4_title: 'Design de UI/UX Responsivo',
        service_s4_desc: 'Designs modernos e vibrantes que impactam seus usuários e transmitem qualidade premium em qualquer tela.',
        service_s5_title: 'Infraestrutura em Nuvem',
        service_s5_desc: 'Modelos de deploy escaláveis na Netlify, Vercel ou AWS com esteiras de CI/CD automatizadas.',
        service_s6_title: 'Enriquecimento de Dados',
        service_s6_desc: 'Extração, processamento e enriquecimento de dados comerciais usando automação em Python e JS.',
        area_badge: 'Área de Atendimento',
        area_title: 'Atendemos Ely, Cambridge & Região de Cambridgeshire',
        area_desc1: 'Com base em Ely, oferecemos serviços completos de manutenção de imóveis, incluindo pintura, carpintaria e instalação de cozinhas.',
        area_desc2: 'Não tem certeza se atendemos a sua área? Ligue para nós. Somos flexíveis e atendemos por toda a região.',
        area_label: 'Áreas que Atendemos',
        contact_title: 'Solicite Seu Orçamento Grátis',
        contact_desc: 'Preencha o formulário e retornaremos em até 2 horas. Prefere falar? Ligue para nós.',
        contact_phone_label: 'Ligue ou WhatsApp',
        contact_email_label: 'E-mail',
        contact_hours_label: 'Horário de Atendimento',
        contact_hours_val: 'Seg.–Sáb., 7h–18h',
        contact_reason_title: 'Por que nos escolhem',
        contact_r1: 'Orçamentos escritos gratuitos, sem compromisso',
        contact_r2: 'Preços fixos sem custos ocultos',
        contact_r3: 'Organizados, profissionais e respeitosos',
        contact_r4: 'Totalmente segurados com cobertura de até £5M',
        contact_form_title: 'Conte-nos Sobre o Seu Projeto',
        contact_form_name: 'Nome',
        contact_form_name_ph: 'Seu nome',
        contact_form_phone: 'Telefone',
        contact_form_phone_ph: 'Melhor número para contato',
        contact_form_email: 'E-mail',
        contact_form_email_ph: 'Seu endereço de e-mail',
        contact_form_service: 'Serviço Necessário',
        contact_form_submit: 'Solicitar Orçamento',
        contact_success_title: 'Mensagem Recebida!',
        contact_success_desc: 'Obrigado. Entraremos em contato em até 2 horas.',
        contact_field_project: 'Conte-nos Sobre Seu Projeto',
        contact_field_project_ph: 'Ex: Apartamento em Cambridge, precisa de pintura completa...',
        contact_reply_time: 'Geralmente respondemos em até 2 horas. Sem compromisso.',
        gallery_img1_label: 'Dashboard de CRM Customizado',
        gallery_img2_label: 'Soluções de E-commerce',
        gallery_img3_label: 'Fluxos de Agentes de IA',
        gallery_img4_label: 'Diretório de Apps Next.js',
        footer_desc: 'Manutenção de casas, serviços de faz-tudo, pintura, carpintaria, cozinhas, banheiros e paisagismo em Cambridgeshire.',
        footer_privacy: 'Política de Privacidade',
        footer_terms: 'Termos de Serviço',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('EN');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
